@host = http://localhost:5005
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMzkzYjhjYi1kMWQ2LTQ1NzUtOWM0MS1lODljYjMxODIyNzIiLCJlbWFpbCI6ImRhdmUyMjMyQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJkYXZlMjIzMiIsInVzZXJJZCI6ImMzOTNiOGNiLWQxZDYtNDU3NS05YzQxLWU4OWNiMzE4MjI3MiIsImp0aSI6IjcyMmE5Yjc2LTQwMmEtNDNkYy04MDA0LTg3ZjM5YzA0MDFjNCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJyb2xlIjoidXNlciIsImV4cCI6MTc1MDk1NDYzOSwiaXNzIjoiTXlCbG9nLkFwaSIsImF1ZCI6Ik15QmxvZy5DbGllbnQifQ.TWpvxigCgmpumA4JVK9NHEiTHgC45NTpQRkl-AyKirM
@token2 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMTFkYjFjNS1kMDQ4LTQ1ZTMtOGQ1MC01ZTMzMDQwNDczMDYiLCJlbWFpbCI6InR0ZGF0MjIzMkBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoidHRkYXQyMjMyIiwidXNlcklkIjoiYzExZGIxYzUtZDA0OC00NWUzLThkNTAtNWUzMzA0MDQ3MzA2IiwianRpIjoiMWNkNmIwODAtNTRkNy00MzQ2LWFmYjUtNGU2YTQwMzE4ZmUxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzUxMjkxNTc5LCJpc3MiOiJNeUJsb2cuQXBpIiwiYXVkIjoiTXlCbG9nLkNsaWVudCJ9.hzwa1eWYXMCdXzPqbCvQiwWu7rtuTRjZn54vxC_79Ng
### Get Blogs
GET {{host}}/api/blogs
Content-Type: application/json
Authorization: {{token}} 


### Create blos
POST {{host}}/api/blogs
Content-Type: application/json
Authorization: {{token2}}

{
  "title": "The Rising Impact of Analytics in Professional Sports",
  "content": "Analytics have become a cornerstone in the evolution of professional sports, influencing everything from player recruitment to in-game tactics. Teams now leverage real-time data to optimize lineups, monitor player health, and gain a competitive edge. For example, soccer clubs use tracking systems to analyze player movement and fatigue, while baseball franchises rely on predictive models to determine pitching rotations and batting orders. The integration of analytics has also enhanced fan engagement, with interactive statistics and visualizations becoming standard in broadcasts. As technology advances, the role of analytics in shaping strategies and outcomes across all major sports is only expected to grow.",
  "status": 1,
  "categoryId": "e48a5154-6ba2-4555-9b9c-1dfce3d0bd55",
  "publishDate": "2025-06-30T09:30:00Z",
  "isDraft": false
}

### Add comment to blog
POST {{host}}/api/blogs/78029818-206a-461a-8683-a783921ba470/comments
Content-Type: application/json
Authorization: {{token2}}

{
  "content": "this article is helpful children",
  "parentCommentId": "e263fcd9-97cd-473e-bf0a-09f21ddf84c4"
}


### Get blog by Id
GET  {{host}}/api/blogs/78029818-206a-461a-8683-a783921ba470

### Get blog by slug
GET  {{host}}/api/blogs/slug/the-rising-impact-of-analytics-in-professional-sports

### Add like
PATCH  {{host}}/api/blogs/78029818-206a-461a-8683-a783921ba470/like
Authorization: {{token}}