@host = http://localhost:5295

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "usernameOrEmail": "ttdat2232@example.com",
    "password": "your-password"
}

### Register
POST {{host}}/api/auth/register
Content-Type: application/json

{
    "username": "dave2232",
    "email": "dave2232@example.com",
    "password": "your-password"
}