name: MyBlog .NET Core

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    strategy:
      matrix:
        configuration: [Debug, Release]
        dotnet-version: [9.0.x]
    env:
      solution-name: MyBlog.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore ${{env.solution-name}}

      - name: Build project
        run: dotnet build ${{env.solution-name}}
