name: MyBlog Angluar

on:
  push:
    branches: ["main"]
    paths:
      - "MyBlog.Web/**"
  pull_request:
    branches: ["main"]
    paths:
      - "MyBlog.Web/**"

jobs:
  angular:
    name: Angular Build
    runs-on: [self-hosted, Windows, X64]
    strategy:
      matrix:
        node-version: [22.12.0]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
